runtime: php55
api_version: 1

env_variables:
  SRV_ENG: 'gcloud'

error_handlers:
  - file: error_pages/default_error.html

  - error_code: dos_api_denial
    file: error_pages/dos_api_denial.html

handlers:
- url: /static
  static_dir: static

- url: /api/.*
  script: api.php

- url: /export/.*
  script: export.php

- url: /.*
  script: app.php

skip_files:
  - .htaccess
  - .git/.*
  - ^(.*)\.ignore\.(php|js|css|png|ini|md)$
  - tally-export/.*
